### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by grassroadsZ** [txiuqw4/farmersworld-bot#3]
hello ,thansk for you  project ,but when i used it ,it did not  work well ,no eosjs, ,did i need npm install eosjs first?

**Comment by txiuqw4** [comment]
@grassroadsZ you just run command npm install. it will install all dependencies.

**Comment by grassroadsZ** [comment]
thanks for you answer, but i use wax cloud wallet ,if i wanted use api call this game, can you give me some api doc? i can not find nice doc ,i like use python more than js ...

**Comment by txiuqw4** [comment]
You can look some links below. hope it helps you
[https://github.com/EOSIO/eosjs](https://github.com/EOSIO/eosjs)
[https://github.com/worldwide-asset-exchange/waxjs](https://github.com/worldwide-asset-exchange/waxjs)
[How To Submit A Transaction](https://developers.eos.io/manuals/eosjs/latest/how-to-guides/how-to-submit-a-transaction)
[Chain API](https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_api_plugin/api-reference/index)
[Farmersworld contract](https://wax.bloks.io/account/farmersworld?loadContract=true&tab=Tables&account=farmersworld&scope=farmersworld&limit=100)
if you use wax cloud wallet, I think you can use [selenium](https://github.com/SeleniumHQ/Selenium) to handle login and sign your transaction
