### ISSUE TITLE
How to automatically replenish energy

### ISSUE THREAD

**Issue by wxz52155** [txiuqw4/farmersworld-bot#7]
my set：
    "TIMEZONE": "Asia/Hong_Kong",
    "REPAIR_IF_DURABILITY_LOWER": 100,
    "RECOVER_IF_ENERGY_LOWER": 200,
    "LOWEST_ENERGY": 60,
    "MINIMUM_FEE": 5,
    "MINIMUN_WITHDRAW": 500,
    "WITHDRAWABLE": ["WOOD"],
    "PAYBW": false

There is enough food in the account, but it can't replenish energy automatically

**Comment by wxz52155** [comment]
"PAYBW": true

paybw.json It's set up, too

BUT Still prompt
Not enough energy, please eat food to get more energy

**Comment by txiuqw4** [comment]
It will recover energy when energy is lower than LOWEST_ENERGY
